export const userConstants={

    SIGN_IN_REQUEST:"SIGN_IN_REQUEST",
    SIGN_IN_SUCESS:"SIGN_IN_SUCESS",
    SIGN_IN_FAILURE:"SIGN_IN_FAILURE",

    SIGN_UP_REQUEST:"SIGN_UP_REQUEST",
    SIGN_UP_SUCESS:"SIGN_UP_SUCESS",
    SIGN_UP_FAILURE:"SIGN_UP_FAILURE"


}

